# SORT OPTIONS:
#
# 'timestamp' - will trim oldest first
#
# 'alphanumeric'  - will trim '01.log' first
#    ['01.log', '1.log', '2.log', '3.log']
#
# 'alphanumeric-reverse' - will trim '3.log' first
#    ['3.log', '2.log', '1.log', '01.log']

sort: 'timestamp'

# how many files you want to keep
history: 100

# the path to look for log files in
path: '/tmp/logs'

# the regex expression that log files must match to be considered for deletion
log_regex: '.*\.log$'
